### PR TITLE
Update unl_multisite module

### PR DESCRIPTION
**Pull request by ericras**

### CODE REVIEW

**Comment by macburgee1** [comment]
Quick question - why change the location for drush packages to 'drush/Commands/contrib'?

**Comment by ericras** [comment]
Because there was an existing file in /drush/Commands (https://github.com/unlcms/project-herbie/blob/master/drush/Commands/PolicyCommands.php) so then any additional things put in that folder would need individual entries in .gitignore.

Now, that file (https://github.com/unlcms/project-herbie/blob/master/drush/Commands/PolicyCommands.php) is from the original use of drupal-composer's drupal-project.  Should we just remove that and undo my commit?

**Comment by macburgee1** [comment]
That's a good catch. I missed that when I replaced the Composer scaffolding. Let's remove PolicyCommands.php and then we don't need to namespace with 'contrib'.

**Comment by ericras** [comment]
Updated and ready for review

**Pull request merged**
