### PR TITLE
Book page/config

### PR DESCRIPTION
**Pull request by ericras**
While any node can be added to a 'book' and books aren't even necessary if you're using Menu Block, I've found our people like having a Book node type.  It also eases the cognitive load that Book page = book navigation = book.

### CODE REVIEW

**Comment by ericras** [comment]
fa9e74c3acad6be7fc095e2437a2909c1e022d6a
09a745b64e53e502b4fdc661fe72dfa1991376e5

**Comment by macburgee1** [comment]
## Patch 2827910
The `allow-top-item-to-show-2827910-26-D8.patch` file should be downloaded from Drupal.org instead of being committed to the codebase.

There appears to be an issue with the patch. On a new installation, there is a config mismatch:
Screen Shot 2019-05-21 at 9 46 22 AM
Recommend fixing the patch.

## Redundant Navigation
There are two sets of navigation on book pages - 1) second sidebar and 2) below content. What do you think about removing the set that's below the content?
screenshot

## Active State
There's an issue with Drupal core regarding the active state: [Include 'is_active' value in book tree items](https://www.drupal.org/project/drupal/issues/3056149). Let's patch core to resolve.
There's a corresponding issue for unl_five: https://github.com/unlcms/unl_five/issues/9. I'll have a pull request by EOD.

**Comment by ericras** [comment]
1. If patch files disappear from drupal.org then we're screwed.  That happened to me once - a file was deleted.  IMO we should have our own copy of necessary patches.  I'll look at the mismatch.

2. Some users have complained about redundant navigation in 7 before.  I think its useful - the links that appear at the bottom of the page are a continuation (subpages) of the content on the page.

**Comment by macburgee1** [comment]
Re patches, that does make sense. I've never run into that issue, but it's definitely possible. Files attached to issues aren't protected the same way that commits are. #74

Re redundant navigation, let's kick that issue over to the group tomorrow.

**Comment by ericras** [comment]
1) Patch 2827910

I don't think it is a problem with the patch.  I'm thinking I did something dumb like hand edit the config file and put a '1' instead of true.  I've updated the config 6e2ef14 

2) Redundant Navigation

Keep as-is.

3) Active State

d29e05c  adds the 'is_active' patch and updates unl_five

**Pull request merged**
