### PR TITLE
Add Generic Content Block

### PR DESCRIPTION
**Pull request by macburgee1**

### CODE REVIEW

**Comment by macburgee1** [comment]
In addition to creating a generic content block, I also updated Layout Builder Restrictions to the new 8.x-2.x version (8.x-1.x is now unsupported) and configured the restrictions.

**Comment by macburgee1** [comment]
I expect we'll get some feedback on the name during beta

**Comment by ericras** [comment]
I’m trying to make sure we get the absolute perfect machine name from day 1. T O P P R I O R I T Y

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by macburgee1** [comment]
Possible alternatives:

1) Generic content
2) Editor
3) Rich text
4) WYSIWYG

**Pull request merged**
