### PR TITLE
Create Contact Info custom block type

### PR DESCRIPTION
**Pull request by macburgee1**
Are we going to attempt to do fields for contact us block? Even with it chunked into fields, there is probably a need for a wysiwyg (html? ugh) dumping ground for complex contact info.

### CODE REVIEW

**Comment by skoolbus39** [comment]
I'd like to see structured data added to the contact info. I also support having the option to link addresses to buildings in UNL Maps.

**Comment by macburgee1** [comment]
I agree with adding the map link. Let's remember to discuss at our weekly meeting on 1/6.

Here's the underlying issue, as I see it:
We want campus websites to use UNL Maps (not Google Maps or some other service); however, not all of the sites using this project are on campus or can be mapped with UNL Maps. For these Google Maps may be the best option. Can UNL Maps be conditionally mandated? Or is this a documentation/training issue?

**Comment by macburgee1** [comment]
Per weekly meeting, we're going to support only UNL maps at this point.

**Comment by macburgee1** [comment]
Follow-up issues: #175 #176

**Comment by macburgee1** [comment]
Unassigned, pending D8.8.1 update

**Comment by macburgee1** [comment]
Master, including D8.8.1, is merged. Re-assigning for review

**Comment by macburgee1** [comment]
**Organization name in the schema**
I added 'name' and 'url' attributes, which were left as TODO's in a comment.

**Description**
Description is added.

**Contact Info Margin**
This wasn't functioning as intended. I fixed that. It now inserts 1em of margin. I also used the [Markup](https://www.drupal.org/project/markup) module to add some help text on the form field.

The reason I added this was to give site builders the ability to add what visually appears to be a new paragraph but maintains the structured data (i.e. not have an open text field).

**Default content**
We could do something like this at install. The annoying thing is that Drupal will ignore `hook_install()` for a profile if you're installing from existing config. We'd have to put in a 'unl_default_content' module or something. I'm fine tackling in a follow-up issue.

**Comment by ericras** [comment]
The Markup backend content is showing on the front end
Screen Shot 2020-02-14 at 2 17 42 PM

**Comment by ericras** [comment]
I suppose it's just as simple as disabling the markup field on /admin/structure/paragraphs_type/contact_info_margin/display

**Comment by macburgee1** [comment]
That was it! Change made.

**Pull request merged**
