### PR TITLE
Create 'Card + Circle Image' Block Type

### PR DESCRIPTION
**Pull request by macburgee1**
(We need a better name for this block type.)

- Headline
  - Text
  - Required
- Headline Link
  - Link
  - URL only; no link text
  - Optional
  - Headline is rendered as link if Headline Link is populated
- Body
  - Rich text
  - Required
  - Add new text format (Body Block Centered); based on Body Block with lists removed as those won't work well with centered text
- Image
  - Image
  - ~~Optional~~ Required
  - Ratio: 1:1
  - Offer image border option?
- CTA
  - Link
  - Both URL and link text are required
  - Optional

### CODE REVIEW

**Comment by macburgee1** [comment]
Note: inverse behavior is also accounted before.

**Comment by ericras** [comment]
I am not seeing dcf-inverse cascade down:

Screen Shot 2019-09-05 at 1 58 52 PM

**Comment by ericras** [comment]
It's because `$variables['element']['#object']->__get('#section_classes');` is not looking at section class packages

**Comment by ericras** [comment]
Oh jeez 2eb69b3 is what is in #125 - sorry

**Comment by macburgee1** [comment]
When I was working on #125, I should have thought about this PR. I just pushed a commit that updates the Headline field template to mirror that of the Card block type. That fixes an issue where dcf-inverse only gets applied to the headline if it's a link.

**Pull request merged**
