### PR TITLE
Create Details/Summary (Accordion) Block Type

### PR DESCRIPTION
**Pull request by macburgee1**
image

Fields:
- Items
  - Paragraph
    - Title
      - Text
      - Required
    - Body
      - Text Area
      - Required

Section title will be set in Layout Builder section settings.

### CODE REVIEW

**Comment by ericras** [comment]
This block type has a contextual edit button (?) - https://github.com/unlcms/project-herbie/pull/90#issuecomment-519644660

**Comment by macburgee1** [comment]
The Inline Block Title Automatic module has been added in #90, so when that PR is merged, I'll rework this PR. I'm good with creating a new field. That will give us the flexibility to name it within the context of its use (e.g. Headline vs Title).

Re contextual link, that's correct. I didn't remove `{{ title_prefix }}` and `{{ title_suffix }}` from block--block_content-accordion--full.html.twig like I did with the Card block template file, so the Accordion block's contextual links didn't break.

Note to self: Remove view-mode designator for Accordion block template.

**Comment by macburgee1** [comment]
Blocked by #90

**Comment by macburgee1** [comment]
This PR has been updated and is ready to be reviewed.

**Pull request merged**
