### PR TITLE
Only allow local site HTML pages to be linked in menu

### PR DESCRIPTION
**Pull request by macburgee1**
- No PDF
- No external website

### CODE REVIEW

**Comment by ericras** [comment]
This is really cool.

I think the big issue is that it only allows nodes to be linked.  I think we want Views, Webforms, Taxonomy pages, etc to be allowed too.  Really, anything that is a valid internal path should be allowed.

**Comment by macburgee1** [comment]
I think we should implement a whitelist of permissible routes.

Re Webforms, I don't think we should expose them directly to the public. The path will be inconsistent with the content hierarchy. http://example.com/form/schedule-a-tour vs http://example.com/visit/schedule-a-tour.

So far, aside from webforms, we have taxonomy terms and views. Anything else come to mind? We can always add routes in the future.

**Comment by ericras** [comment]
I would lean to allowing everything and blacklisting something if needed. (That shouldn't really be needed anyway since if a user doesn't have access to something it doesn't show anyway.)

Regarding webforms: People are going to want to put those in the menu.  There's the "Webform URL alias" setting - doesn't that allow you to set the form path to "/visit/schedule-a-tour" ?

**Comment by macburgee1** [comment]
Per discussion, the unl_menu module has been changed from a whitelist to a blacklist model for internal routes. External URLs and unrouted paths continue to be invalid in all instances.

**Comment by ericras** [comment]
The error message change in 9345e7b missed a second place a few lines up where 'Only nodes and the front page ("<front>") can be linked in a menu item.' needs to be changed to 'The path <em>@uri</em> is not allowed'

After that, it can be merged.

**Pull request merged**
