### PR TITLE
Create Cards Block Type

### PR DESCRIPTION
**Pull request by macburgee1**
Fields:
- Headline
  - Text
  - Required
- Headline Link
  - Link
  - URL only; no link text
  - Optional
  - Headline is rendered as link if Headline Link is populated
- Body
  - Rich text
  - Required
  - New text format/editor
    - Allowed tags: `<em>`, `<strong>`, `<sup>`, `<sub>`, `<a>`, `<ul>`, `<ol>`, `<li>`
    - See issue #99
- Subhead
  - Text
  - Optional
- Overline
  - Text
  - Optional
- Image
  - Image
  - Optional
  - Ratio: 2:1
- CTA
  - Link
  - Both URL and link text are required
  - Optional
- CTA Style
  - Select
  - Displayed and required if CTA is populated
  - Options: Primary (default), Secondary
- Presentation
  - Select
  - Options: Transparent, Solid

Use field descriptions to provide guidance how to use certain fields, such as overline vs subhead and CTAs. If both Headline Link and CTA are populated, then uses markup element and #states to display warning message.

todo - Decide if images that are in transparent presentation should have option to present with/without border.

### CODE REVIEW

**Comment by macburgee1** [comment]
Taking back to implement dcf-inverse changes in #110

**Comment by macburgee1** [comment]
Changes made

**Comment by ericras** [comment]
### No Contextual Edit button

When editing a node through the layout tab there is no contextual button to edit an existing card.

### Headline vs Title

Is there a reason to have a separate Headline field instead of using Title for that purpose?  If there needs to be both (so the Title can be used on the administrative side?) then the Display Title checkbox doesn't make sense since it doesn't display regardless.

**Comment by macburgee1** [comment]
Re `#1`, that's a Drupal core issue: [Contextual links of reusable content blocks are not displayed when rendering entities built via Layout Builder](https://www.drupal.org/project/drupal/issues/3020876). 

Re `#2`, I believe the [Inline Block Title Automatic](https://www.drupal.org/project/inline_block_title_automatic) module addresses this issue.

My vote is that we defer `#1` with a follow-up issue and include `#2` with this PR (with the latter subject to review under this PR).

**Comment by ericras** [comment]
### 3 Unable to add image

TypeError: Argument 3 passed to _block_form_alter_block_type_form_alter_invoke() must be of the type string, null given, called in /Library/WebServer/Documents/workspace/herbiesandbox/web/modules/contrib/block_form_alter/block_form_alter.module on line 84 in _block_form_alter_block_type_form_alter_invoke() (line 98 of /Library/WebServer/Documents/workspace/herbiesandbox/web/modules/contrib/block_form_alter/block_form_alter.module) #0

**Comment by macburgee1** [comment]
Interesting.. can you provide steps to reproduce? Argument 3 should be a form_id string, I believe...

**Comment by ericras** [comment]
We'll need to follow up on #1 because not being able to edit existing content is a pretty big deal.

I think that module for #2 looks good. My first inclination is to not have a headline field and just use the title.... but for consistency with reusable blocks where that's used for the administrative block description, I think that module makes sense.

**Comment by ericras** [comment]
3 - I'm just creating a card inside the layout builder. Then uploading an image and writing alt text.  Then when I click "Add Block" nothing happens visually, the ajax call returns:

```
AjaxError: 
An AJAX HTTP error occurred.
HTTP Result Code: 200
Debugging information follows.
Path: /workspace/herbiesandbox/web/layout_builder/add/block/overrides/node.4/0/content/inline_block%3Acard?_wrapper_format=drupal_dialog&ajax_form=1
StatusText: OK
ResponseText: 
```

and the thing before was the PHP error that was logged

**Comment by ericras** [comment]
3 - during the ajax upload it works fine and $block_type = 'card'.  But when the "Add Block" button is clicked then block_type = null

**Comment by macburgee1** [comment]
Ok. I'll look in to that

**Comment by ericras** [comment]
Upon clicking "Add Block", block_form_alter_form_alter() is not executed if I've added an image so that temp value (block_form_alter--block-type) doesn't get created.  Can't figure out why yet

**Comment by ericras** [comment]
A fix I came up with without fully understanding the flow is that _block_form_alter_block_type_form_alter_inline_block_process() needs to be able to generate $block_type.

`function _block_form_alter_block_type_form_alter_inline_block_process(array &$element, FormStateInterface &$form_state) {


  $build_info = $form_state->getBuildInfo();
  $block = $build_info['callback_object']->getCurrentComponent();
  $component_config = $block->get('configuration');

  $block_id = explode(':', $component_config['id']);
  $plugin_id = $block_id[0];

  // Inline blocks.
  if ($plugin_id == 'inline_block') {
    $block_type = $block_id[1];
  }



  $block_type = isset($form_state->getTemporaryValue('block_form_alter--block-type')) ? $form_state->getTemporaryValue('block_form_alter--block-type') : $block_type;
  _block_form_alter_block_type_form_alter_invoke($element, $form_state, $block_type);
  return $element;
}`

**Comment by macburgee1** [comment]
The Block Form Alter issue was addressed here: https://www.drupal.org/project/block_form_alter/issues/3074355

**Comment by macburgee1** [comment]
I believe I misunderstood the contextual links issue. The aforementioned core issue is to render contextual links on the front end (e.g. /node/1), whereas the actual issue was that contextual links failed to render in layout builder (e.g. /node/1/layout). This issue was caused by missing markup in block--block-content-card.html.twig. I added back `{{ title_prefix }}` and `{{ title_suffix }}` to resolve the issue.

**Comment by macburgee1** [comment]
The Inline Block Title Automatic has been added. I believe all issues raised during the PR review have been addressed.

**Pull request merged**
